name: Go Test

on: [push]

jobs:
  gobuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: go build
        run: go build cmd/bot/main.go

  govet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: go vet
        run: go vet -v ./...

  gostaticcheck:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2

      -   name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17

      -   name: go staticcheck
          uses: dominikh/staticcheck-action@v1.1.0
